title: ZBluePhoenix
subtitle: 蓝色妖凰
description: null
author: ZBluePhoenix
language: zh-CN
timezone: null
url: 'http://zbluephoenix.cn'
root: /
permalink: ':year/:month/:day/:title/'
permalink_defaults: null
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link: true
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: null
default_category: uncategorized
category_map: null
tag_map: null
date_format: YYYY-MM-DD
time_format: 'HH:mm:ss'
per_page: 10
pagination_dir: page
theme: next
deploy:
  type: git
  repo:
    github: 'git@github.com:zbluephoenix/zbluephoenix.github.io.git,master'
theme_config:
  cache:
    enable: true
  minify: false
  custom_file_path: null
  scheme: Muse
  darkmode: true
  favicon:
    small: /images/favicon-16x16-next.png
    medium: /images/favicon-32x32-next.png
    apple_touch_icon: /images/apple-touch-icon-next.png
    safari_pinned_tab: /images/logo.svg
  custom_logo: null
  creative_commons:
    license: by-nc-sa
    sidebar: false
    post: false
    language: null
  menu:
    home: / || fa fa-home
    categories: /categories/ || fa fa-th
    archives: /archives/ || fa fa-archive
  menu_settings:
    icons: true
    badges: true
  sidebar:
    position: right
    display: post
    padding: 18
    offset: 12
  avatar:
    url: /images/avatar.png
    rounded: true
    rotated: false
  site_state: true
  social:
    GitHub: 'https://github.com/zbluephoenix || fab fa-github'
    E-Mail: 'mailto:zbluephoenix@163.com || fa fa-envelope'
  social_icons:
    enable: true
    icons_only: false
    transition: false
  links_settings:
    icon: fa fa-globe
    title: Links
    layout: block
  links:
    墨娘: 'https://www.imoniang.com'
  toc:
    enable: true
    number: true
    wrap: false
    expand_all: false
    max_depth: 6
  chat:
    enable: false
    icon: fa fa-comment
    text: Chat
  language_switcher: false
  footer:
    since: 2016
    icon:
      name: fa fa-heart
      animated: false
      color: '#ff0000'
    copyright: null
    powered: true
    beian:
      enable: false
      icp: null
      gongan_id: null
      gongan_num: null
      gongan_icon_url: null
  excerpt_description: true
  read_more_btn: true
  post_meta:
    item_text: true
    created_at: true
    updated_at:
      enable: true
      another_day: true
    categories: true
  symbols_count_time:
    separated_meta: true
    item_text_total: false
  tag_icon: false
  reward_settings:
    enable: false
    animation: false
  reward: null
  follow_me: null
  related_posts:
    enable: false
    title: null
    display_in_home: false
    params:
      maxCount: 5
  post_edit:
    enable: false
    url: 'https://github.com/user-name/repo-name/tree/branch-name/subdirectory-name/'
  post_navigation: left
  tagcloud:
    min: 12
    max: 30
    amount: 200
    orderby: name
    order: 1
  calendar:
    calendar_id: <required>
    api_key: <required>
    orderBy: startTime
    showLocation: false
    offsetMax: 72
    offsetMin: 4
    showDeleted: false
    singleEvents: true
    maxResults: 250
  preconnect: false
  text_align:
    desktop: justify
    mobile: justify
  mobile_layout_economy: false
  android_chrome_color: '#222'
  codeblock:
    theme:
      light: default
      dark: tomorrow-night
    prism:
      light: prism
      dark: prism-dark
    copy_button:
      enable: false
      style: null
  back2top:
    enable: true
    sidebar: false
    scrollpercent: false
  reading_progress:
    enable: false
    position: top
    color: '#37c6c0'
    height: 3px
  bookmark:
    enable: false
    color: '#222'
    save: auto
  github_banner:
    enable: true
    permalink: 'https://github.com/zbluephoenix'
    title: Follow me on GitHub
  font:
    enable: false
    host: null
    global:
      external: true
      family: Lato
      size: null
    title:
      external: true
      family: null
      size: null
    headings:
      external: true
      family: null
      size: null
    posts:
      external: true
      family: null
    codes:
      external: true
      family: null
  disable_baidu_transformation: false
  index_with_subtitle: false
  exturl: false
  google_site_verification: null
  bing_site_verification: null
  yandex_site_verification: null
  baidu_site_verification: null
  baidu_push: false
  math:
    every_page: false
    mathjax:
      enable: false
    katex:
      enable: false
      copy_tex: false
  pjax: false
  fancybox: false
  mediumzoom: false
  lazyload: false
  pangu: false
  quicklink:
    enable: false
    home: false
    archive: false
    delay: true
    timeout: 3000
    priority: true
    ignores: null
  comments:
    style: tabs
    active: null
    storage: true
    lazyload: false
    nav: null
  disqus:
    enable: false
    shortname: null
    count: true
  disqusjs:
    enable: false
    api: null
    apikey: null
    shortname: null
  changyan:
    enable: false
    appid: null
    appkey: null
  valine:
    enable: false
    appId: null
    appKey: null
    serverURLs: null
    placeholder: Just go go
    avatar: mm
    meta:
      - nick
      - mail
      - link
    pageSize: 10
    lang: null
    visitor: false
    comment_count: true
    recordIP: false
    enableQQ: false
    requiredFields: []
  livere_uid: null
  gitalk:
    enable: false
    github_id: null
    repo: null
    client_id: null
    client_secret: null
    admin_user: null
    distraction_free_mode: true
    language: null
  rating:
    enable: false
    id: null
    color: '#fc6423'
  add_this_id: null
  google_analytics:
    tracking_id: null
    only_pageview: false
  baidu_analytics: null
  growingio_analytics: null
  cnzz_siteid: null
  leancloud_visitors:
    enable: false
    app_id: null
    app_key: null
    server_url: null
    security: true
  firestore:
    enable: false
    collection: articles
    apiKey: null
    projectId: null
  busuanzi_count:
    enable: true
    total_visitors: true
    total_visitors_icon: fa fa-user
    total_views: true
    total_views_icon: fa fa-eye
    post_views: true
    post_views_icon: far fa-eye
  algolia_search:
    enable: false
    hits:
      per_page: 10
  local_search:
    enable: true
    trigger: auto
    top_n_per_article: 1
    unescape: false
    preload: false
  swiftype_key: null
  chatra:
    enable: false
    async: true
    id: null
  tidio:
    enable: false
    key: null
  note:
    style: simple
    icons: false
    light_bg_offset: 0
  tabs:
    transition:
      tabs: false
      labels: true
  pdf:
    enable: false
    height: 500px
  mermaid:
    enable: false
    theme: forest
  motion:
    enable: true
    async: false
    transition:
      post_block: fadeIn
      post_header: fadeInDown
      post_body: fadeInDown
      coll_header: fadeInLeft
      sidebar: fadeInUp
  nprogress:
    enable: false
    spinner: true
  canvas_ribbon:
    enable: false
    size: 300
    alpha: 0.6
    zIndex: -1
  vendors:
    internal: local
    plugins: jsdelivr
    anime: null
    fontawesome: null
    prism: null
    prism_autoloader: null
    prism_line_numbers: null
    mathjax: null
    katex: null
    copy_tex_js: null
    copy_tex_css: null
    pjax: null
    jquery: null
    fancybox_js: null
    fancybox_css: null
    mediumzoom: null
    lazyload: null
    pangu: null
    quicklink: null
    disqusjs_js: null
    disqusjs_css: null
    valine: null
    gitalk_js: null
    gitalk_css: null
    firebase_app: null
    firebase_firestore: null
    algolia_search: null
    instant_search: null
    mermaid: null
    animate_css: null
    nprogress_js: null
    nprogress_css: null
    canvas_ribbon: null
  css: css
  js: js
  images: images
